### ISSUE TITLE
图生图会crash

### ISSUE THREAD

**Issue by likunpm** [godly-devotion/MochiDiffusion#253] opened 2023-05-06 10:55 UTC
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

32GB

### What happened?

图生图 crash

**Comment by vzsg** [comment] 2023-05-06 11:06
Potentially a duplicate of https://github.com/godly-devotion/MochiDiffusion/issues/248.

**Comment by likunpm** [comment] 2023-05-06 11:37
> Potentially a duplicate of #248.

thx，I have seen the way to fix it。

**Comment by likunpm** [comment] 2023-05-06 11:49
> Potentially a duplicate of #248.

Does version 3.1 only support images with a size of 512x512?

**Comment by vzsg** [comment] 2023-05-07 06:42
Unfortunately, yes. I fixed img2img's non-square image support after Mochi 3.1. The fix wasn't released separately, and shortly after that the Apple library had breaking changes... It's not a great position.

On the bright side, only one component of the pipeline changed: the VAEEncoder. And there aren't as many different VAEs around than checkpoints. If someone already reconverted the VAE used by your model, you can just replace that one package by hand.

I suggest hitting up Mochi's Discord server and asking about it in the models channel.

**Closed** 2023-05-07 18:37 UTC
Labels: bug
