### ISSUE TITLE
I run SDXL model is crash

### ISSUE THREAD

**Issue by zqchris** [godly-devotion/MochiDiffusion#300] opened 2023-08-01 08:08 UTC
### Processor

M1 Max (or later)

### Memory

64GB (or higher)

### What happened?

SDXL model download from:
https://huggingface.co/apple/coreml-stable-diffusion-xl-base/tree/main
and put into the model folder , run generate and crash

### Crash Log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mochi Diffusion [52559]
Path:                  /Applications/Mochi Diffusion.app/Contents/MacOS/Mochi Diffusion
Identifier:            com.joshua-park.Mochi-Diffusion
Version:               4.1.3 (4.1.3)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-01 16:08:28.8966 +0800
OS Version:            macOS 13.4.1 (22F770820d)
Report Version:        12
Anonymous UUID:        5FCA2C63-00FB-C7E1-80B5-DD3B6ECEEFE7

Sleep/Wake UUID:       94FF96CE-1502-4B54-BB2C-FE0C543667B0

Time Awake Since Boot: 210000 seconds
Time Since Wake:       8932 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010432a88c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [52559]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19ff8ff14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19ffa2240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19ff98b78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19ff90290 mach_msg + 24
4   CoreFoundation                	       0x1a00ae7e4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a00ad0c4 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a00ac4b8 CFRunLoopRunSpecific + 612
7   HIToolbox                     	       0x1a98f6c40 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x1a98f6a7c ReceiveNextEventCommon + 648
9   HIToolbox                     	       0x1a98f67d4 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x1a32cdd44 _DPSNextEvent + 636
11  AppKit                        	       0x1a32ccee0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  AppKit                        	       0x1a32c1344 -[NSApplication run] + 464
13  AppKit                        	       0x1a3298794 NSApplicationMain + 880
14  SwiftUI                       	       0x1c836f6b8 0x1c82d4000 + 636600
15  SwiftUI                       	       0x1c94d05ac 0x1c82d4000 + 18859436
16  SwiftUI                       	       0x1c8d50c48 0x1c82d4000 + 10996808
17  Mochi Diffusion               	       0x104290578 0x10428c000 + 17784
18  dyld                          	       0x19fc77f28 start + 2236

Thread 1 Crashed:
0   Mochi Diffusion               	       0x10432a88c 0x10428c000 + 649356
1   Mochi Diffusion               	       0x104329c24 0x10428c000 + 646180
2   Mochi Diffusion               	       0x10432aa70 0x10428c000 + 649840
3   Mochi Diffusion               	       0x104325750 0x10428c000 + 628560
4   Mochi Diffusion               	       0x1042c5840 0x10428c000 + 235584
5   Mochi Diffusion               	       0x1042e7ae5 0x10428c000 + 375525
6   Mochi Diffusion               	       0x1042ecb01 0x10428c000 + 396033
7   Mochi Diffusion               	       0x1042ea545 0x10428c000 + 386373
8   Mochi Diffusion               	       0x1042ecb15 0x10428c000 + 396053
9   libswift_Concurrency.dylib    	       0x22d67a215 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 2:
0   libsystem_pthread.dylib       	       0x19ffcad8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19ffcad8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x19ffcad8c start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19ff8ff14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19ffa2240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19ff98b78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19ff90290 mach_msg + 24
4   CoreFoundation                	       0x1a00ae7e4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a00ad0c4 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a00ac4b8 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x1a33f8334 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x19ffcffa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x19ffcada0 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x19ffcad8c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x19ffcad8c start_wqthread + 0

Thread 8:: H11ANEServicesThread
0   libsystem_kernel.dylib        	       0x19ff8ff14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19ffa2240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19ff98b78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19ff90290 mach_msg + 24
4   CoreFoundation                	       0x1a00ae7e4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a00ad0c4 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a00ac4b8 CFRunLoopRunSpecific + 612
7   CoreFoundation                	       0x1a013157c CFRunLoopRun + 64
8   ANEServices                   	       0x1b74d992c H11ANE::H11ANEServicesThreadStart(H11ANE::H11ANEServicesThreadParams*) + 132
9   libsystem_pthread.dylib       	       0x19ffcffa8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x19ffcada0 thread_start + 8


Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x00006000034dabb0
    x4: 0x0000000000000004   x5: 0x0000000000002b80   x6: 0x00006000034dab80   x7: 0x00000001a872b6b5
    x8: 0x0000000000000155   x9: 0x0000000000000154  x10: 0x0000000000002b80  x11: 0x00000000000007fb
   x12: 0x00000000bfe64885  x13: 0x00000000000007fd  x14: 0x00000000c00650e9  x15: 0x00000000bfe64885
   x16: 0x00000000000000e9  x17: 0x0000000040000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x00006000034dab80  x21: 0x0000000000000000  x22: 0x000060000395e2f0  x23: 0x0000000000000000
   x24: 0x000000010fe22e00  x25: 0x000060000393a3e0  x26: 0x000000015001a4d0  x27: 0x00006000034bc270
   x28: 0x000000016bbfa710   fp: 0x000000016bbfa860   lr: 0x496280010432a7e0
    sp: 0x000000016bbfa730   pc: 0x000000010432a88c cpsr: 0x60001000
   far: 0x0000000158148000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x10428c000 -        0x10436ffff com.joshua-park.Mochi-Diffusion (4.1.3) <aaa2d12b-f1a1-3358-9d4b-4419750941db> /Applications/Mochi Diffusion.app/Contents/MacOS/Mochi Diffusion
       0x1044dc000 -        0x10451ffff org.sparkle-project.Sparkle (2.4.2) <0ad1c5c8-fdc4-32cf-90fa-869442d175ac> /Applications/Mochi Diffusion.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10fd7c000 -        0x10fd87fff libobjc-trampolines.dylib (*) <570c31f7-94c6-3b86-ae44-1694db0a4bcd> /usr/lib/libobjc-trampolines.dylib
       0x19ff8f000 -        0x19ffc8fe7 libsystem_kernel.dylib (*) <34a49b54-82b2-37a1-9314-f6a4a2bb3ff8> /usr/lib/system/libsystem_kernel.dylib
       0x1a002f000 -        0x1a0508fff com.apple.CoreFoundation (6.9) <203e4401-8c2e-3157-a24b-92f52551d43e> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a98c6000 -        0x1a9bf9fff com.apple.HIToolbox (2.1.1) <d800278b-4e6c-3032-b56f-027a938a51d6> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1a3295000 -        0x1a41a3fff com.apple.AppKit (6.9) <041c7d21-21cc-3eea-ae53-d39f5ca6a24e> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1c82d4000 -        0x1c9b6bfff com.apple.SwiftUI (4.5.6.2.402) <bfc2b09d-5fd4-3298-ba44-b8d7a458e0ca> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x19fc72000 -        0x19fd00553 dyld (*) <2237410f-d39c-30ce-9a94-13aacb66b766> /usr/lib/dyld
       0x22d632000 -        0x22d68cffb libswift_Concurrency.dylib (*) <a60d651e-1f8b-35b9-a760-f4e4b0647f32> /usr/lib/swift/libswift_Concurrency.dylib
       0x19ffc9000 -        0x19ffd5fff libsystem_pthread.dylib (*) <46d35233-a051-3f4f-bba4-ba56dddc4d1a> /usr/lib/system/libsystem_pthread.dylib
       0x1b74c9000 -        0x1b74e8fff com.apple.ANEServices (6.551) <cb38d918-d13b-3ed6-bfce-f71ef63d59b0> /System/Library/PrivateFrameworks/ANEServices.framework/Versions/A/ANEServices

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 3520K        4 
CG image                          1504K       33 
ColorSync                          592K       30 
CoreAnimation                     6000K      124 
CoreGraphics                        32K        2 
CoreGraphics (reserved)             16K        1         reserved VM address space (unallocated)
CoreUI image data                 6048K       48 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           515.4M       73 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)           1.0G        9         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           256.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                       3248K       12 
__AUTH                            1856K      344 
__AUTH_CONST                      28.1M      567 
__CTF                               824        1 
__DATA                            12.8M      555 
__DATA_CONST                      27.5M      573 
__DATA_DIRTY                      1978K      212 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       802.2M        4 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2011K        1 
__TEXT                           612.0M      592 
dyld private memory                272K        2 
mapped file                      553.5M       58 
shared memory                     2960K       19 
===========                     =======  ======= 
TOTAL                              3.9G     3303 
TOTAL, minus reserved VM space     2.7G     3303 



-----------
Full Report
-----------

{"app_name":"Mochi Diffusion","timestamp":"2023-08-01 16:08:29.00 +0800","app_version":"4.1.3","slice_uuid":"aaa2d12b-f1a1-3358-9d4b-4419750941db","build_version":"4.1.3","platform":1,"bundleID":"com.joshua-park.Mochi-Diffusion","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4.1 (22F770820d)","roots_installed":0,"name":"Mochi Diffusion","incident_id":"C21FD275-8FCC-45B6-88BF-D36010098A73"}
{
  "uptime" : 210000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,5",
  "coalitionID" : 30972,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F770820d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-01 16:08:28.8966 +0800",
  "incident" : "C21FD275-8FCC-45B6-88BF-D36010098A73",
  "pid" : 52559,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-01 16:07:59.9878 +0800",
  "procStartAbsTime" : 5122706958362,
  "procExitAbsTime" : 5123400622799,
  "procName" : "Mochi Diffusion",
  "procPath" : "\/Applications\/Mochi Diffusion.app\/Contents\/MacOS\/Mochi Diffusion",
  "bundleInfo" : {"CFBundleShortVersionString":"4.1.3","CFBundleVersion":"4.1.3","CFBundleIdentifier":"com.joshua-park.Mochi-Diffusion"},
  "storeInfo" : {"deviceIdentifierForVendor":"A41E20CE-5A4F-5C49-9E0F-2FEF3005498A","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.joshua-park.Mochi-Diffusion",
  "crashReporterKey" : "5FCA2C63-00FB-C7E1-80B5-DD3B6ECEEFE7",
  "codeSigningID" : "com.joshua-park.Mochi-Diffusion",
  "codeSigningTeamID" : "TCQ6328PP6",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 8932,
  "sleepWakeUUID" : "94FF96CE-1502-4B54-BB2C-FE0C543667B0",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x000000010432a88c","rawCodes":[1,4365396108],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":52559},
  "os_fault" : {"process":"Mochi Diffusion"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":2557651,"queue":"com.apple.main-thread","frames":[{"imageOffset":3860,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":78400,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":3},{"imageOffset":39800,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":3},{"imageOffset":4752,"symbol":"mach_msg","symbolLocation":24,"imageIndex":3},{"imageOffset":522212,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":4},{"imageOffset":516292,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":4},{"imageOffset":513208,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":4},{"imageOffset":199744,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":5},{"imageOffset":199292,"symbol":"ReceiveNextEventCommon","symbolLocation":648,"imageIndex":5},{"imageOffset":198612,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":5},{"imageOffset":232772,"symbol":"_DPSNextEvent","symbolLocation":636,"imageIndex":6},{"imageOffset":229088,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":716,"imageIndex":6},{"imageOffset":181060,"symbol":"-[NSApplication run]","symbolLocation":464,"imageIndex":6},{"imageOffset":14228,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":6},{"imageOffset":636600,"imageIndex":7},{"imageOffset":18859436,"imageIndex":7},{"imageOffset":10996808,"imageIndex":7},{"imageOffset":17784,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":8}]},{"triggered":true,"id":2557668,"threadState":{"x":[{"value":1},{"value":0},{"value":0},{"value":105553171688368},{"value":4},{"value":11136},{"value":105553171688320},{"value":7121057461,"symbolLocation":21,"symbol":"_OBJC_$_INSTANCE_METHODS_MLPredictionOptions"},{"value":341},{"value":340},{"value":11136},{"value":2043},{"value":3219540101},{"value":2045},{"value":3221639401},{"value":3219540101},{"value":233},{"value":1073741824},{"value":0},{"value":0},{"value":105553171688320},{"value":0},{"value":105553176421104},{"value":0},{"value":4561448448},{"value":105553176273888},{"value":5637252304},{"value":105553171563120},{"value":6102689552}],"flavor":"ARM_THREAD_STATE64","lr":{"value":5287929654340134880},"cpsr":{"value":1610616832},"fp":{"value":6102689888},"sp":{"value":6102689584},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4365396108,"matchesCrashFrame":1},"far":{"value":5772705792}},"frames":[{"imageOffset":649356,"imageIndex":0},{"imageOffset":646180,"imageIndex":0},{"imageOffset":649840,"imageIndex":0},{"imageOffset":628560,"imageIndex":0},{"imageOffset":235584,"imageIndex":0},{"imageOffset":375525,"imageIndex":0},{"imageOffset":396033,"imageIndex":0},{"imageOffset":386373,"imageIndex":0},{"imageOffset":396053,"imageIndex":0},{"imageOffset":295445,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":9}]},{"id":2557669,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":2557678,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":2557689,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":2557693,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3860,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":78400,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":3},{"imageOffset":39800,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":3},{"imageOffset":4752,"symbol":"mach_msg","symbolLocation":24,"imageIndex":3},{"imageOffset":522212,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":4},{"imageOffset":516292,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":4},{"imageOffset":513208,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":4},{"imageOffset":1454900,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":6},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":2557916,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":2557917,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":2557926,"name":"H11ANEServicesThread","frames":[{"imageOffset":3860,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":3},{"imageOffset":78400,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":3},{"imageOffset":39800,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":3},{"imageOffset":4752,"symbol":"mach_msg","symbolLocation":24,"imageIndex":3},{"imageOffset":522212,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":4},{"imageOffset":516292,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":4},{"imageOffset":513208,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":4},{"imageOffset":1058172,"symbol":"CFRunLoopRun","symbolLocation":64,"imageIndex":4},{"imageOffset":67884,"symbol":"H11ANE::H11ANEServicesThreadStart(H11ANE::H11ANEServicesThreadParams*)","symbolLocation":132,"imageIndex":11},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4364746752,
    "CFBundleShortVersionString" : "4.1.3",
    "CFBundleIdentifier" : "com.joshua-park.Mochi-Diffusion",
    "size" : 933888,
    "uuid" : "aaa2d12b-f1a1-3358-9d4b-4419750941db",
    "path" : "\/Applications\/Mochi Diffusion.app\/Contents\/MacOS\/Mochi Diffusion",
    "name" : "Mochi Diffusion",
    "CFBundleVersion" : "4.1.3"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4367171584,
    "CFBundleShortVersionString" : "2.4.2",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "0ad1c5c8-fdc4-32cf-90fa-869442d175ac",
    "path" : "\/Applications\/Mochi Diffusion.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2028"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4560764928,
    "size" : 49152,
    "uuid" : "570c31f7-94c6-3b86-ae44-1694db0a4bcd",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6978859008,
    "size" : 237544,
    "uuid" : "34a49b54-82b2-37a1-9314-f6a4a2bb3ff8",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6979514368,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5087232,
    "uuid" : "203e4401-8c2e-3157-a24b-92f52551d43e",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1977"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7139516416,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "d800278b-4e6c-3032-b56f-027a938a51d6",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7032360960,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15790080,
    "uuid" : "041c7d21-21cc-3eea-ae53-d39f5ca6a24e",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.60.124"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7653376000,
    "CFBundleShortVersionString" : "4.5.6.2.402",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 25788416,
    "uuid" : "bfc2b09d-5fd4-3298-ba44-b8d7a458e0ca",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "4.5.6.2.402"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6975594496,
    "size" : 582996,
    "uuid" : "2237410f-d39c-30ce-9a94-13aacb66b766",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9351405568,
    "size" : 372732,
    "uuid" : "a60d651e-1f8b-35b9-a760-f4e4b0647f32",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6979096576,
    "size" : 53248,
    "uuid" : "46d35233-a051-3f4f-bba4-ba56dddc4d1a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7370215424,
    "CFBundleShortVersionString" : "6.551",
    "CFBundleIdentifier" : "com.apple.ANEServices",
    "size" : 131072,
    "uuid" : "cb38d918-d13b-3ed6-bfce-f71ef63d59b0",
    "path" : "\/System\/Library\/PrivateFrameworks\/ANEServices.framework\/Versions\/A\/ANEServices",
    "name" : "ANEServices",
    "CFBundleVersion" : "6.551"
  }
],
  "sharedCache" : {
  "base" : 6974930944,
  "size" : 3551657984,
  "uuid" : "f5b60d87-3ee7-3c74-8415-517f8103a187"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 3520K        4 \nCG image                          1504K       33 \nColorSync                          592K       30 \nCoreAnimation                     6000K      124 \nCoreGraphics                        32K        2 \nCoreGraphics (reserved)             16K        1         reserved VM address space (unallocated)\nCoreUI image data                 6048K       48 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           515.4M       73 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)           1.0G        9         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           256.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                       3248K       12 \n__AUTH                            1856K      344 \n__AUTH_CONST                      28.1M      567 \n__CTF                               824        1 \n__DATA                            12.8M      555 \n__DATA_CONST                      27.5M      573 \n__DATA_DIRTY                      1978K      212 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       802.2M        4 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2011K        1 \n__TEXT                           612.0M      592 \ndyld private memory                272K        2 \nmapped file                      553.5M       58 \nshared memory                     2960K       19 \n===========                     =======  ======= \nTOTAL                              3.9G     3303 \nTOTAL, minus reserved VM space     2.7G     3303 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "b7e03c5c54bf73a295e6fd33cf3dd77adf4ca310",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "62c74108bcb0435c2153f963",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "64b1c8ec9aa41116c95f6da1"
      },
      "deploymentId" : 240000283
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "8ca8349c-e2bc-482c-9ca7-3907b48a5341",
      "experimentId" : "648b5a581b04c12d4127bbb6",
      "deploymentId" : 400000002
    }
  ]
}
}

Model: Mac14,5, BootROM 8422.121.1, proc 12:8:4 processors, 96 GB, SMC 
Graphics: Apple M2 Max, Apple M2 Max, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr 15 2023 07:04:38 version 23.20.84.0.40.50.94 FWID 01-a7cc62f5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

**Comment by jrittvo** [comment] 2023-08-01 10:03
The current version of Mochi Diffusion does not support SDXL models. Look for support to be added in a future release.

**Comment by godly-devotion** [comment] 2023-08-01 20:54
Duplicate of #295

**Closed by godly-devotion** 2023-08-01 20:54 UTC
Labels: bug, duplicate
