### ISSUE TITLE
Delete multiple Images at once

### ISSUE THREAD

**Issue by Schneppi** [godly-devotion/MochiDiffusion#356] opened 2023-12-15 11:28 UTC
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Please allow us to select more than just 1 Image at a time and to delete all selected Images at once.
Would be nice if Keyboard Shortcuts like CMD+a or clicking multiple Images while holding Shift or CMD and so on, would also work.
Thank you.

### Why do you think this should be added?

Would speed up cleaning up the Gallery.

**Comment by godly-devotion** [comment] 2023-12-15 15:55
Duplicate of #146.

**Closed by godly-devotion** 2023-12-15 15:55 UTC
Labels: duplicate, enhancement
