### ISSUE TITLE
[Bug]: Stuck on "Loading Model..."

### ISSUE THREAD

**Issue by Myridium** [godly-devotion/MochiDiffusion#104] opened 2023-01-22 11:55 UTC
### Running Latest Version

- [x] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

I enter a prompt, set the settings, set a model, then click "Generate". The spinning wheel says "Loading Model..."

![Screenshot 2023-01-22 at 22 55 16](https://user-images.githubusercontent.com/6416952/213914455-cabfe72a-43cc-4b46-a532-a52fcd4624bc.png)

It does not progress beyond this point.

I used the Mochi Diffusion app earlier without issue. Same model, same prompt. It could have happened after I updated to the newest version of Mochi Diffusion (2.1.2). However, downgrading to 2.1.1 did not help.

I tried deleting the application and application settings, but some settings keep persisting. I deleted the two directories in "/Users/user/Library/", but still some settings persist. When I remove the app and reinstall it, it remembers the prompt I used and directory of the models. I think the application is storing data somewhere nonstandard, that is not labelled with the application name "mochi". I could not find any remaining directories on the machine with "mochi" in the name; I performed a search with ```sudo find / -iname mochi```.

**Comment by MDMAchine** [comment] 2023-01-23 14:38
I've had this happen and a reboot resolved the issue. Is it still happening?

**Comment by Myridium** [comment] 2023-01-26 03:33
That seemed to resolve the issue for now.

**Comment by godly-devotion** [comment] 2023-01-26 14:14
Apple just released macOS 13.2. It might include some improvements for Neural Engine.

**Comment by Myridium** [comment] 2023-01-28 05:11
Could you please address my other concern? 

> I tried deleting the application and application settings, but some settings keep persisting. I deleted the two directories in "/Users/user/Library/", but still some settings persist. When I remove the app and reinstall it, it remembers the prompt I used and directory of the models. I think the application is storing data somewhere nonstandard, that is not labelled with the application name "mochi". I could not find any remaining directories on the machine with "mochi" in the name; I performed a search with `sudo find / -iname mochi`.

**Comment by godly-devotion** [comment] 2023-01-28 05:25
The configuration file is in the standard place. `~/Library/Preferences/com.joshua-park.Mochi-Diffusion.plist`

**Comment by Myridium** [comment] 2023-02-01 06:49
> The configuration file is in the standard place. `~/Library/Preferences/com.joshua-park.Mochi-Diffusion.plist`

I deleted this file, opened Mochi Diffusion, and the settings still persist.

**Comment by godly-devotion** [comment] 2023-02-25 04:10
Since I can't reproduce this and is most likely a Core ML issue, I will be closing this.

**Closed by godly-devotion** 2023-02-25 04:10 UTC
Labels: bug
