### ISSUE TITLE
Add better samplers

### ISSUE THREAD

**Issue by calben99** [godly-devotion/MochiDiffusion#264] opened 2023-06-19 03:35 UTC
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Because the UI does not have any sampler selection, I assume you are just using Euler A? It would be really nice to be able to use higher quality, samplers, especially DPM++ SDE Karras.  

### Why do you think this should be added?

I have found that when using stable diffusion, DPM++ SDE Karras is by far the best simpler, also for latent upscale. Mochi diffusion is 3X as fast as stable diffusion, so I love it, but can't generate anything photo realistic without a better sampler.

**Comment by jrittvo** [comment] 2023-06-19 03:49
The Mochi UI calls them "schedulers" rather than "samplers", and there are 2 available in the Settings at present.  One is DPM-Solver++ which is a flavor very close to the DPM++ SDE Karras that you like.  Euler A is slowly working its way into the Apple package that Mochi is based on.  The other one now in Mochi is PNDM, which I think goes back to very early implementations of Stable Diffusion.

**Comment by jrittvo** [comment] 2023-06-19 03:59
The base model also has a lot to do with getting photo realistic results.  Is there a particular model that you use outside of Mochi that we can add to suit your workflow?  We're always looking for suggestions of new models to add to the repo.

**Comment by calben99** [comment] 2023-06-19 05:24
Interesting!  So Latent upscale would be a great add on, using the existing scheduler.

**Comment by godly-devotion** [comment] 2023-06-19 15:14
Duplicate of #113.

**Closed by godly-devotion** 2023-06-19 15:14 UTC
Labels: duplicate, enhancement, coreml-issue
